### PR TITLE
feat: create a new post

### LINKED ISSUE #2: a script that will create a new post in your site, and update .., eventually pushing ...
## a script that will create a new post in your site, and update some meta data information (version - see below), eventually pushing the changes back to github.

- Prepare a script (choose whichever language) that will take one parameter:
    - either `dev`, in which case, it will:
        - create a new post using markdown with yaml frontmatter format,
        - use the output of `[fortune](http://manpages.ubuntu.com/manpages/xenial/man6/fortune.6.html)` command as content,
        - and increment the version of the site by `0.0.1`,
        - compile the site,
        - commit and push the sources (markdown files) and build site (html) back to github
    - or `staging`, in which case, it will:
        - take the last known version of the site,
        - increment the version of the site by `0.1.x` (e.g. move from `0.1.5` to `0.2.0`)
        - compile the site
        - commit, tag and pus to github

### LINKED ISSUE #6: Create a new post in your site
Create a new post in your site

- either `dev`, in which case, it will:
    - create a new post using markdown with yaml frontmatter format,
    - use the output of `[fortune](http://manpages.ubuntu.com/manpages/xenial/man6/fortune.6.html)` command as content,

_Originally posted by @jizusun in https://github.com/jizusun/devops-homework-wiredcraft/issues/2#issuecomment-768866970_

### PR DESCRIPTION
**Pull request by jizusun**
close #6

### CODE REVIEW

**Comment by jizusun** [comment]
@ilyamochalov

I should have listened to your tip 🤦
> TIP: don't "over-engineer" the system and do only what is stated in the task.  

But TDD and CI for golang really took me some time, sorry for this 🚑

Can you have a quick check? ♥️

**Comment by ilyamochalov** [comment]
@jizusun Jizu, your progress looks fine. Please stick to the objectives of the task ;)

**Comment by jizusun** [comment]
> @jizusun Jizu, your progress looks fine. Please stick to the objectives of the task ;)

Thank you so much 😛
Can you help to approve it?

**Review by ilyamochalov — APPROVED** [review]
lgtm

**Pull request merged**
